job('First-Maven-Project-Via-DSL') {
    description("First Maven Job, Generated by the DSL on ${new Date()}, The Project is a Small Maven Project Hosted on Github")
    scm {
        git("https://github.com/AbhishekKumar1602/JenkinsTutorial.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'jenkins-maven-sample/single-module/pom.xml')
    }
    publishers {
        archiveArtifacts '**/*.jar'
    }
}